Repository virtual-kubelet/virtual-kubelet, pull requests merged in 2019-06, with the labels that each got.

#643 Allow composing env var from existing env vars.
  Gopkg.lock
  vendor/k8s.io/kubernetes/third_party/forked/golang/expansion/expand.go
  vkubelet/env.go
  vkubelet/env_internal_test.go
Labels: feature

#648 Support error handler callback for node status
  cmd/virtual-kubelet/commands/root/root.go
  test/e2e/node_test.go
  vkubelet/node.go
  vkubelet/node_test.go
Labels: feature

#672 Allow setting tracer in the context.
  trace/trace.go
Labels: enhancement

#680 Add provider method to pass node configuration
  cmd/virtual-kubelet/commands/root/node.go
  providers/mock/mock.go
  providers/provider.go
Labels: enhancement, feature

#682 Update README links to providers READMEs
  README.md
Labels: documentation

#683 version: ensure Kubernetes v1.13.7
  cmd/virtual-kubelet/main.go
  go.mod
  go.sum
Labels: enhancement
