Repository virtual-kubelet/virtual-kubelet, pull requests merged in 2019-07, with the labels that each got.

#695 e2e: misc improvements
  .circleci/config.yml
  Makefile.e2e
  hack/skaffold/virtual-kubelet/skaffold.yml
Labels: bug, enhancement

#696 skaffold target requires .SECONDEXPANSION
  Makefile.e2e
Labels: bug

#699 e2e: cleanup after run
  Makefile.e2e
Labels: enhancement

#702 Add godoc to the repo root.
  doc.go
  errdefs/doc.go
Labels: documentation
