Repository virtual-kubelet/virtual-kubelet, pull requests merged in 2019-09, with the labels that each got.

#754 Update docs on virtual-kubelet.io
  website/content/docs/providers.md
  website/content/docs/usage.md
  website/data/cli.yaml
Labels: documentation

#751 Have NotifyPods store the pod status in a map
  node/pod.go
  node/podcontroller.go
  node/queue.go
Labels: enhancement

#759 Test pods going missing while they're running in legacy providers
  node/lifecycle_test.go
  node/pod.go
Labels: enhancement, testing

#758 Importable End-To-End Test Suite
  README.md
  go.mod
  go.sum
  internal/test/e2e/framework/env.go
  internal/test/e2e/framework/framework.go
  internal/test/e2e/framework/node.go
  internal/test/e2e/framework/pod.go
  internal/test/e2e/main_test.go
  internal/test/suite/suite.go
  internal/test/suite/suite_test.go
  test/e2e/README.md
  test/e2e/basic.go
  test/e2e/node.go
  test/e2e/suite.go
Labels: enhancement, testing

#735 Add methods to wait for pod controller exit and errors
  cmd/virtual-kubelet/internal/commands/root/root.go
  node/doc.go
  node/lifecycle_test.go
  node/pod_test.go
  node/podcontroller.go
  node/podcontroller_test.go
Labels: feature
