Repository virtual-kubelet/virtual-kubelet, pull requests merged in 2021-01, with the labels that each got.

#943 e2e: test with Kubernetes to 1.20.1
  .circleci/config.yml
  hack/skaffold/virtual-kubelet/skaffold.yml
  test/e2e/README.md
Labels: chore

#942 build: use Go 1.15
  .circleci/config.yml
  Dockerfile
  Makefile
  go.mod
Labels: chore

#947 log: fix klog depth and output format
  log/klogv2/klogv2.go
  log/klogv2/klogv2_test.go
Labels: bug

#949 log: fix klogv2.WithField(s)
  log/klogv2/klogv2.go
Labels: bug

#951 Update mailing list link
  README.md
Labels: bug, documentation
