Repository virtual-kubelet/virtual-kubelet, pull requests merged in 2023-06, with the labels that each got.

#1112 Add Stackpath provider
  website/data/providers.yaml
Labels: provider

#1121 Update providers.yaml - StackPath
  website/data/providers.yaml
Labels: documentation

#1122 fix: Fix opentelemetry dependencies issues
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  internal/podutils/helper.go
  internal/test/e2e/main_test.go
  node/pod.go
  node/podcontroller.go
  trace/opentelemetry/opentelemetry.go
  trace/opentelemetry/opentelemetry_test.go
Labels: bug

#1102 add portforwarding support to node/api
  cmd/virtual-kubelet/internal/provider/mock/mock.go
  internal/kubernetes/portforward/constants.go
  internal/kubernetes/portforward/httpstream.go
  internal/kubernetes/portforward/httpstream_test.go
  internal/kubernetes/portforward/portforward.go
  internal/kubernetes/portforward/websocket.go
  internal/kubernetes/portforward/websocket_test.go
  node/api/portforward.go
  node/api/server.go
  node/nodeutil/provider.go
Labels: kind/feature
